
title: Washington University Mock Trial
#email: your-email@example.com
description: >
  The website of Washington University's award-winning Mock Trial team.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: WUMT

# Build settings
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-feed
  - jekyll-assets
#
collections:
  members:
    output: true
  recruitment:
    output: false
  faqs:
    output: false
  rounds:
    output: false
  arch:
    output: true
    permalink: /:name


assets:
  autowrite: true
  prefix: "/assets"
  digest: true

#uncss:
#  stylesheets:            # a list of stylesheets to be processed; mandatory
#    - _site/assets/style-*.css
#  files:                  # html files to consider, globs are supported; default: **/*.html
#    - "_site/*.html"
#  compress: true          # compress resulting css with sass; default: false
#  ignore:                 # always keep rules for these selectors; default: none
#    - ".is-loading"
#    - "#titleBar"
#  media:                  # additional media queries to consider; default: undefined
#    - print
#  timeout: 30             # how long to wait for the JS to be loaded; default: undefined