
title: Washington University Mock Trial
#email: your-email@example.com
description: >
  The website of Washington University's award-winning Mock Trial team.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: WUMT

# Build settings
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-feed
  - jekyll-assets
#
collections:
  members:
    output: true
  recruitment:
    output: false
  faqs:
    output: false

assets:
  autowrite: true
  prefix: "/assets"
  digest: true
