backend:
  name: github
  repo: alexweil/wumt # Path to your Github repository
  branch: master # Branch to update

media_folder: "_assets/img/uploads"
public_folder: "/images/uploads"

collections:
  - name: "members" # Used in routes, e.g. /admin/collections/blog
    label: "Member" # Used in the UI
    folder: "_data/members" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "member"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Title", name: "title", widget: "string",  required: false}
      - {label: "Role", widget: "select", options: ["Member", "Coach"]}
      - {label: "Join Year", name: "joinYear", widget: "number", default: 2017}
      - {label: "Graduation Year", name: "graduationYear", widget: "number", default: 2021,  required: false}
      - {label: "Majors & Minors", name: "majors", widget: "string",  required: false}
      - {label: "Picture", name: "picture", widget: "image",  required: false}
      - {label: "Hometown", name: "hometown", widget: "string",  required: false}
      - {label: "Biography", name: "biography", widget: "markdown",  required: false}