backend:
  name: github
  repo: alexjweil/wumt # Path to your Github repository
  branch: master # Branch to update
#  site_domain: cms.netlify.com
#  base_url: https:/api.netlify.com

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "members" # Used in routes, e.g. /admin/collections/blog
    label: "Members" # Used in the UI
    folder: "_members" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "member"}
      - {label: "Name", name: "title", widget: "string", required: true}
      - {label: "Title", name: "teamTitle", widget: "string",  required: false}
      - {label: "Role", widget: "select", options: ["", "Member", "Coach"], required: true}
      - {label: "Join Year", name: "joinYear", widget: "number", default: 2017}
      - {label: "Graduation Year", name: "graduationYear", widget: "number", default: 2021,  required: false}
      - {label: "Majors", name: "majors", widget: "string",  required: false}
      - {label: "Minors", name: "minors", widget: "string",  required: false}
      - {label: "Photo", name: "photo", widget: "image",  required: false}
      - {label: "Hometown", name: "hometown", widget: "string",  required: false}
      - {label: "Biography", name: "biography", widget: "markdown",  required: false}

  - name: "about" # Used in routes, e.g. /admin/collections/blog
    label: "FAQs" # Used in the UI
    folder: "_faqs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Question", name: "title", widget: "string"}
      - {label: "Answer", name: "answer", widget: "markdown",  required: false}

  - name: "recruitment"
    label: "Recruitment"
    folder: "_recruitment"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Main Message", name: "main_message", widget: "markdown", required: true}
      - name: "groups"
        label: "Groups"
        widget: "list"
        fields:
          - {label: "Name", name: "name", widget: "string", required: true}
          - {label: "Message", name: "message", widget: "markdown", required: true}

  - name: "arch"
    label: "Arch"
    folder: "_arch"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", default: "ArchInvitational"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "arch"}
      - {label: "Case Type", name: "caseType", widget: "select", options: ["", "Civil", "Criminal"], required: true}
      - {label: "Photo", name: "photo", widget: "image",  required: false}
      - {label: "Details", name: "details", widget: "markdown", required: true}
      - {label: "Tournament Packet", name: "packet", widget: "file", required: false}
      - {label: "Round 1", name: round1, widget: relation, collection: round, searchFields: [title], valueField: title, required: false}
      - {label: "Round 2", name: round2, widget: relation, collection: round, searchFields: [title], valueField: title, required: false}
      - {label: "Round 3", name: round3, widget: relation, collection: round, searchFields: [title], valueField: title, required: false}
      - {label: "Round 4", name: round4, widget: relation, collection: round, searchFields: [title], valueField: title, required: false}
      - name: schedule
        label: Schedule
        widget: list
        fields:
          - {label: "Event Name", name: "title", widget: "string", required: true}
          - {label: "Start Time", name: "startTime", widget: "datetime", required: true}
          - {label: "Location", name: "location", widget: "string", required: false}


  - name: "round"
    label: "Round Pairings"
    folder: "_rounds"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Round", name: "title", widget: "string", required: true}
      - name: pairings
        label: Pairing
        widget: list
        fields:
          - {label: "Prosecution", name: "prosecution", widget: "string", required: true}
          - {label: "Defense", name: "defense", widget: "string",  required: true}
          - {label: "Location", name: "location", widget: "string", required: true}